server:
  port: 5000

eureka:
  instance:
    hostname: localhost
  client:
    #是否向服务注册中心注册自己,默认为true
    register-with-eureka: false
    #Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
